language: python
python:
  - "3.8"
install: "pip install -r requirements.txt"
script: make publish
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: output
  fqdn: blog.sebastienbarbier.com
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: main
